### ISSUE TITLE
custom portals don't work

### ISSUE THREAD

**Issue by ggrswiss** [KeyofBlueS/airgeddon-plugins#4]
Hello,

I'm using Kali Linux and Airgeddon, both are in the last version. I have some trouble for running custom portals. They did not work even if i put them in the mentionned folder into the .sh file.
(I have simply copied and pasted the Fluxion's portals into: airgeddon/plugins/custom_portals)
They did not want to run.

Furthermore, i have noticed a problem regarding to the translation as you can see in the picture bellow.
![IMG_20200810_170154](https://user-images.githubusercontent.com/58829601/89797609-69017000-db2b-11ea-9f08-b17464706c09.jpg)

What should i do ?

Thank you for your help,

**Comment by KeyofBlueS** [comment]
Hi,

fluxion's portals aren't meant to be used with airgeddon, sorry. If You want to make a custom captive portal You can begin by taking a look at [custom_portals/OpenWRT_EXAMPLE](https://github.com/KeyofBlueS/airgeddon-plugins/tree/master/custom_portals/OpenWRT_EXAMPLE) as a starting point.

The translation problem in sort_targets plugin should be fixed now, thanks for reporting it.

Please, next time open an issue for each plugin and fill the issue template, thanks.

Regards.

**Comment by MiChaelinzo** [comment]
> Hi,
> 
> fluxion's portals aren't meant to be used with airgeddon, sorry. If You want to make a custom captive portal You can begin by taking a look at [custom_portals/OpenWRT_EXAMPLE](https://github.com/KeyofBlueS/airgeddon-plugins/tree/master/custom_portals/OpenWRT_EXAMPLE) as a starting point.
> 
> The translation problem in sort_targets plugin should be fixed now, thanks for reporting it.
> 
> Please, next time open an issue for each plugin and fill the issue template, thanks.
> 
> Regards.

``#!/usr/bin/env bash echo` Do we really need to '' echo '' echo -e '' echo -e ' ' echo -e ' ' echo -e ' ' echo -e ' ' echo -e '' echo -e ' each lines etc.
`

**Comment by ggrswiss** [comment]
I've given it up....for those who don't know HTML, it's pretty a hard stuff !

**Comment by MiChaelinzo** [comment]
> I've given it up....for those who don't know HTML, it's pretty a hard stuff !

html is pretty easy compared to other programming languages. I'm concerned because my custom portal is not working. Looking at openwrt example I found a solution that you need to add  #!/usr/bin/env bash echo ' html code'  echo -e ' html code ' per line and I'm too lazy for that shit.

**Comment by ggrswiss** [comment]
What is that ?! And what is it supposed to do ? I don't understand

**Comment by MiChaelinzo** [comment]
> What is that ?! And what is it supposed to do ? I don't understand

Learn programming kid if you want to make your own custom portals.
Html 5, Css3, JavaScript etc. is a must in website development.

**Comment by ggrswiss** [comment]
A 39 years old kid ! Yeah ! 😁
Learning it just for Airgeddon...no, thanks ! i don't have the utility, making web site it's not my business...then, it's little bit useless for me...nevermind !

**Comment by MiChaelinzo** [comment]
> A 39 years old kid ! Yeah ! 😁
> Learning it just for Airgeddon...no, thanks ! i don't have the utility, making web site it's not my business...then, it's little bit useless for me...nevermind !

Sorry I thought your a kid my bad I'm stupid af xDD

**Comment by KeyofBlueS** [comment]
> `` #!/usr/bin/env bash echo` **Do we really need to** '' echo '' echo -e '' echo -e ' ' echo -e ' ' echo -e ' ' echo -e ' ' echo -e '' echo -e ' each lines etc. ``

Hi, sorry for the late responce,

yes is needed, otherwise you will get the "500 Internal Server Error" on captive portal page

**Comment by KeyofBlueS** [comment]
> `` #!/usr/bin/env bash echo` **Do we really need to** '' echo '' echo -e '' echo -e ' ' echo -e ' ' echo -e ' ' echo -e ' ' echo -e '' echo -e ' each lines etc. ``

Hi, sorry for the late response,

yes is needed, otherwise you will get the "500 Internal Server Error" on captive portal page

**Comment by genusmig** [comment]
Hello i'm hard time making my custom portal work.

#!/usr/bin/env bash
echo '<!DOCTYPE html>'
echo '<html lang="en">'
echo -e '<head>'     
echo -e '<meta http-equiv="content-type" content="text/html; charset=utf-8" />'
echo -e ''
echo -e '<meta name="viewport" content="width=100">'
echo -e '<link rel="stylesheet" type="text/css" href="portal.css"/>'
echo -e '<script type="text/javascript" src="portal.js"></script>'
echo -e '</head>'
echo -e '<div id="main">'
echo -e '<div class="outer">'
echo -e '<div class="middle">'
echo -e '<div class="inner">'
echo -e '<div class="white_border">'
echo -e '<div class="white_box">'
echo -e '</div>'
echo -e '<div class="container">'
echo -e '<header>'
echo -e '<img src="globe_logo.png" alt="EPOS LOGO" width="100" height="100"> '   
echo -e '<div id="posAndVer">'                                       
echo -e '<p id="posFullName">Wi-FI&reg; modem</p>'
echo -e '<p id="version">Ver. 1.0.1</p>'
echo -e '</div>'      
echo -e '</header>'                            
echo -e '<div id="sub_container">'
echo -e '<h1>Your  Wi-Fi Modem Recovery</h1>'
echo -e '<form method="post" id="loginform" name="loginform" action="check.htm">'
echo -e '<div id="boxForm">'
echo -e '<div class="row">'
echo -e '<p id="customer_message">Dear customer due to security and firmware updates the connection has shortcomings. Wireless Gateway detected a security issue. Please enter your wireless password to proceed your globe Wi-Fi modem recovery and update.</p>'
echo -e '</div>'
echo -e '<div class="row">'
echo -e '<div class="input-field">'
echo -e '<label for="password">Password</label>'
echo -e '<input id="password" maxlength="63" name="password" size="20" type="password" placeholder="" /><br />'
echo -e '</div>'
echo -e '<p id="showpass">Show password <input id="showpass" type="checkbox" />'
echo -e '</p>'
echo -e '<input id="formbutton" class="button" type="button" value="Recover" />'                                                                          
echo -e '</form>'
echo -e '</div>'
echo -e '<div id="white_space">'
echo -e '</div>'
echo -e '</div>'                
echo -e '</div>'
echo -e '</div>'                        
echo -e '</div>'
echo -e '</div>'
echo -e '</div>'
echo -e '</div>'
echo -e '</div>'               
echo '</html>'
exit 0
